{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ap2-expense.fullname" . }}
  labels:
    {{- include "ap2-expense.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if and .Values.tls.enabled .Values.tls.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ include "ap2-expense.fullname" . }}-managed-cert
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "ap2-expense.fullname" $ }}-{{ .backend.service.name }}
            port:
              number: {{ .backend.service.port }}
      {{- end }}
  {{- end }}
{{- end }}
