"""
PDF Generation Service for Expense Reports

Generates professional PDF reports for expenses with receipts.
"""

import io
from datetime import datetime
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_RIGHT

from ..models import Expense, User, Organization


class PDFExpenseReportGenerator:
    """Generate PDF reports for expenses"""

    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(
            ParagraphStyle(
                name="CustomTitle",
                parent=self.styles["Heading1"],
                fontSize=24,
                textColor=colors.HexColor("#1a1a1a"),
                spaceAfter=30,
                alignment=TA_CENTER,
            )
        )
        self.styles.add(
            ParagraphStyle(
                name="SectionHeader",
                parent=self.styles["Heading2"],
                fontSize=14,
                textColor=colors.HexColor("#333333"),
                spaceAfter=12,
                spaceBefore=12,
            )
        )

    def generate_expense_report(
        self,
        expenses: List[Expense],
        organization: Organization,
        generated_by: User,
        format_type: str = "pdf",
    ) -> bytes:
        """
        Generate PDF report for expenses

        Args:
            expenses: List of expenses to include
            organization: Organization details
            generated_by: User who generated the report
            format_type: Output format (pdf or csv)

        Returns:
            bytes: PDF file content
        """
        if format_type == "csv":
            return self._generate_csv(expenses)

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )

        # Container for the 'Flowable' objects
        elements = []

        # Add title
        title = Paragraph(
            f"<b>Expense Report</b><br/>{organization.name}",
            self.styles["CustomTitle"],
        )
        elements.append(title)
        elements.append(Spacer(1, 0.2 * inch))

        # Add metadata
        metadata = [
            ["Report Generated:", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
            ["Generated By:", generated_by.full_name or generated_by.username],
            ["Total Expenses:", str(len(expenses))],
            [
                "Total Amount:",
                f"${sum(float(e.amount) for e in expenses):,.2f}",
            ],
        ]

        metadata_table = Table(metadata, colWidths=[2 * inch, 4 * inch])
        metadata_table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#666666")),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        elements.append(metadata_table)
        elements.append(Spacer(1, 0.3 * inch))

        # Add expenses table
        if expenses:
            section_header = Paragraph(
                "<b>Expense Details</b>", self.styles["SectionHeader"]
            )
            elements.append(section_header)

            # Table header
            data = [
                [
                    "Date",
                    "Vendor",
                    "Category",
                    "Amount",
                    "Status",
                    "Submitter",
                ]
            ]

            # Add expense rows
            for expense in expenses:
                data.append(
                    [
                        (
                            expense.date.strftime("%Y-%m-%d")
                            if expense.date
                            else "N/A"
                        ),
                        expense.vendor or "N/A",
                        expense.category.value if hasattr(expense.category, "value") else str(expense.category),
                        f"${float(expense.amount):,.2f}",
                        expense.status.value.upper() if hasattr(expense.status, "value") else str(expense.status).upper(),
                        expense.user_id[:8] + "...",
                    ]
                )

            expense_table = Table(
                data, colWidths=[0.9 * inch, 1.5 * inch, 1 * inch, 0.9 * inch, 0.9 * inch, 1 * inch]
            )
            expense_table.setStyle(
                TableStyle(
                    [
                        # Header row styling
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4A90E2")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, 0), 10),
                        ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                        # Data rows styling
                        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                        ("FONTSIZE", (0, 1), (-1, -1), 9),
                        ("ALIGN", (3, 1), (3, -1), "RIGHT"),  # Amount column
                        ("ALIGN", (4, 1), (4, -1), "CENTER"),  # Status column
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F5F5")]),
                        ("TOPPADDING", (0, 1), (-1, -1), 8),
                        ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
                    ]
                )
            )
            elements.append(expense_table)
        else:
            no_data = Paragraph(
                "<i>No expenses found for this report.</i>", self.styles["Normal"]
            )
            elements.append(no_data)

        elements.append(Spacer(1, 0.3 * inch))

        # Add summary section
        section_header = Paragraph("<b>Summary</b>", self.styles["SectionHeader"])
        elements.append(section_header)

        # Calculate statistics
        total_amount = sum(float(e.amount) for e in expenses)
        approved_expenses = [e for e in expenses if str(e.status).lower() == "approved"]
        pending_expenses = [e for e in expenses if str(e.status).lower() == "pending"]
        rejected_expenses = [e for e in expenses if str(e.status).lower() == "rejected"]

        summary_data = [
            ["Total Expenses:", str(len(expenses))],
            ["Total Amount:", f"${total_amount:,.2f}"],
            ["Approved:", f"{len(approved_expenses)} (${sum(float(e.amount) for e in approved_expenses):,.2f})"],
            ["Pending:", f"{len(pending_expenses)} (${sum(float(e.amount) for e in pending_expenses):,.2f})"],
            ["Rejected:", f"{len(rejected_expenses)} (${sum(float(e.amount) for e in rejected_expenses):,.2f})"],
        ]

        summary_table = Table(summary_data, colWidths=[2 * inch, 3 * inch])
        summary_table.setStyle(
            TableStyle(
                [
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F0F0")),
                ]
            )
        )
        elements.append(summary_table)

        # Add footer
        elements.append(Spacer(1, 0.5 * inch))
        footer_text = Paragraph(
            f"<i>Generated by AP2 Expense Manager on {datetime.utcnow().strftime('%Y-%m-%d at %H:%M UTC')}</i>",
            self.styles["Normal"],
        )
        elements.append(footer_text)

        # Build PDF
        doc.build(elements)

        # Get the value of the BytesIO buffer and return it
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    def _generate_csv(self, expenses: List[Expense]) -> bytes:
        """Generate CSV export"""
        import csv
        import io

        output = io.StringIO()
        writer = csv.writer(output)

        # Write header
        writer.writerow(
            [
                "Date",
                "Vendor",
                "Category",
                "Amount",
                "Status",
                "Description",
                "User ID",
                "Created At",
                "Approved By",
                "Approved At",
            ]
        )

        # Write data
        for expense in expenses:
            writer.writerow(
                [
                    expense.date.strftime("%Y-%m-%d") if expense.date else "",
                    expense.vendor or "",
                    expense.category.value if hasattr(expense.category, "value") else str(expense.category),
                    f"{float(expense.amount):.2f}",
                    expense.status.value if hasattr(expense.status, "value") else str(expense.status),
                    expense.description or "",
                    expense.user_id or "",
                    (
                        expense.created_at.strftime("%Y-%m-%d %H:%M:%S")
                        if expense.created_at
                        else ""
                    ),
                    expense.approved_by or "",
                    (
                        expense.approved_at.strftime("%Y-%m-%d %H:%M:%S")
                        if expense.approved_at
                        else ""
                    ),
                ]
            )

        csv_bytes = output.getvalue().encode("utf-8")
        output.close()
        return csv_bytes
