"""Add expense and AP2 mandate models

Revision ID: 62ba85a4da82
Revises: 005_add_subscription_billing
Create Date: 2025-10-05 22:10:06.015865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql, sqlite

# revision identifiers, used by Alembic.
revision = '62ba85a4da82'
down_revision = '005_add_subscription_billing'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create enum types if they don't exist
    conn = op.get_bind()

    # Check and create expensecategory enum
    result = conn.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expensecategory')"))
    if not result.scalar():
        category_enum = postgresql.ENUM('TRAVEL', 'MEALS', 'SOFTWARE', 'OFFICE_SUPPLIES', 'OTHER', name='expensecategory', create_type=False)
        category_enum.create(conn, checkfirst=False)

    # Check and create expensestatus enum
    result = conn.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expensestatus')"))
    if not result.scalar():
        status_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', name='expensestatus', create_type=False)
        status_enum.create(conn, checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('category', postgresql.ENUM('TRAVEL', 'MEALS', 'SOFTWARE', 'OFFICE_SUPPLIES', 'OTHER', name='expensecategory', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', name='expensestatus', create_type=False), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('intent_mandate_id', sa.String(length=255), nullable=True),
    sa.Column('cart_mandate_id', sa.String(length=255), nullable=True),
    sa.Column('payment_mandate_id', sa.String(length=255), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('compliance_check', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cart_mandate_id'], ['cart_mandates.id'], ),
    sa.ForeignKeyConstraint(['intent_mandate_id'], ['intent_mandates.id'], ),
    sa.ForeignKeyConstraint(['payment_mandate_id'], ['payment_mandates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_created_at'), 'expenses', ['created_at'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_transaction_id'), 'expenses', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.alter_column('cart_mandates', 'items',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cart_mandates_intent_id'), table_name='cart_mandates')
    op.create_index(op.f('ix_cart_mandates_intent_mandate_id'), 'cart_mandates', ['intent_mandate_id'], unique=False)
    op.alter_column('intent_mandates', 'constraints',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.alter_column('payment_mandates', 'audit_trail',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('payment_mandates', 'payment_processor_response',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_mandates_cart_id'), table_name='payment_mandates')
    op.create_index(op.f('ix_payment_mandates_cart_mandate_id'), 'payment_mandates', ['cart_mandate_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.drop_index(op.f('ix_payment_mandates_cart_mandate_id'), table_name='payment_mandates')
    op.create_index(op.f('ix_payment_mandates_cart_id'), 'payment_mandates', ['cart_mandate_id'], unique=False)
    op.alter_column('payment_mandates', 'payment_processor_response',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    op.alter_column('payment_mandates', 'audit_trail',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.alter_column('intent_mandates', 'constraints',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cart_mandates_intent_mandate_id'), table_name='cart_mandates')
    op.create_index(op.f('ix_cart_mandates_intent_id'), 'cart_mandates', ['intent_mandate_id'], unique=False)
    op.alter_column('cart_mandates', 'items',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_transaction_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_at'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
