"""Add recurring expense models

Revision ID: 7e0145d9e30d
Revises: 92c9e0c4ee7b
Create Date: 2025-11-07 01:34:33.253387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7e0145d9e30d'
down_revision = '92c9e0c4ee7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expense_templates',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('TRAVEL', 'MEALS', 'SOFTWARE', 'OFFICE_SUPPLIES', 'OTHER', name='expensecategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='recurringfrequency'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('next_run_date', sa.DateTime(), nullable=False),
    sa.Column('intent_mandate_id', sa.String(length=255), nullable=True),
    sa.Column('auto_submit', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('total_submitted', sa.Integer(), nullable=False),
    sa.Column('last_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intent_mandate_id'], ['intent_mandates.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expense_templates_created_at'), 'recurring_expense_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_recurring_expense_templates_is_active'), 'recurring_expense_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_recurring_expense_templates_next_run_date'), 'recurring_expense_templates', ['next_run_date'], unique=False)
    op.create_index(op.f('ix_recurring_expense_templates_organization_id'), 'recurring_expense_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recurring_expense_templates_user_id'), 'recurring_expense_templates', ['user_id'], unique=False)
    op.create_table('expense_notifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expense_id', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['recurring_expense_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_notifications_created_at'), 'expense_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_expense_notifications_is_read'), 'expense_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_expense_notifications_notification_type'), 'expense_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_expense_notifications_user_id'), 'expense_notifications', ['user_id'], unique=False)
    op.create_table('scheduled_expenses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expense_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['recurring_expense_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_expenses_scheduled_date'), 'scheduled_expenses', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_scheduled_expenses_status'), 'scheduled_expenses', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_expenses_template_id'), 'scheduled_expenses', ['template_id'], unique=False)
    op.drop_table('billing_tiers')
    op.drop_index('ix_billing_events_event_type', table_name='billing_events')
    op.drop_index('ix_billing_events_occurred_at', table_name='billing_events')
    op.drop_index('ix_billing_events_organization_id', table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index('idx_usage_org_period', table_name='usage_metrics')
    op.drop_index('idx_usage_reported', table_name='usage_metrics')
    op.drop_index('ix_usage_metrics_organization_id', table_name='usage_metrics')
    op.drop_index('ix_usage_metrics_period_end', table_name='usage_metrics')
    op.drop_index('ix_usage_metrics_period_start', table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index('ix_organization_subscriptions_organization_id', table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tier_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tier_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gcp_account_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('gcp_entitlement_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('marketplace_order_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('billing_period_start', sa.DATETIME(), nullable=True),
    sa.Column('billing_period_end', sa.DATETIME(), nullable=True),
    sa.Column('next_billing_date', sa.DATETIME(), nullable=True),
    sa.Column('trial_start', sa.DATETIME(), nullable=True),
    sa.Column('trial_end', sa.DATETIME(), nullable=True),
    sa.Column('is_trial', sa.BOOLEAN(), nullable=False),
    sa.Column('current_period_usage', sqlite.JSON(), nullable=True),
    sa.Column('usage_alerts_sent', sqlite.JSON(), nullable=True),
    sa.Column('additional_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gcp_account_id')
    )
    op.create_index('ix_organization_subscriptions_organization_id', 'organization_subscriptions', ['organization_id'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('metric_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('metric_value', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), nullable=False),
    sa.Column('period_start', sa.DATETIME(), nullable=False),
    sa.Column('period_end', sa.DATETIME(), nullable=False),
    sa.Column('reported_at', sa.DATETIME(), nullable=True),
    sa.Column('reported_to_gcp', sa.BOOLEAN(), nullable=False),
    sa.Column('report_response', sqlite.JSON(), nullable=True),
    sa.Column('additional_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_metrics_period_start', 'usage_metrics', ['period_start'], unique=False)
    op.create_index('ix_usage_metrics_period_end', 'usage_metrics', ['period_end'], unique=False)
    op.create_index('ix_usage_metrics_organization_id', 'usage_metrics', ['organization_id'], unique=False)
    op.create_index('idx_usage_reported', 'usage_metrics', ['reported_to_gcp', 'period_end'], unique=False)
    op.create_index('idx_usage_org_period', 'usage_metrics', ['organization_id', 'period_start', 'period_end'], unique=False)
    op.create_table('billing_events',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('event_data', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_events_organization_id', 'billing_events', ['organization_id'], unique=False)
    op.create_index('ix_billing_events_occurred_at', 'billing_events', ['occurred_at'], unique=False)
    op.create_index('ix_billing_events_event_type', 'billing_events', ['event_type'], unique=False)
    op.create_table('billing_tiers',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tier_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('base_price_monthly', sa.FLOAT(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('limits', sqlite.JSON(), nullable=False),
    sa.Column('overage_pricing', sqlite.JSON(), nullable=True),
    sa.Column('features', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_name')
    )
    op.drop_index(op.f('ix_scheduled_expenses_template_id'), table_name='scheduled_expenses')
    op.drop_index(op.f('ix_scheduled_expenses_status'), table_name='scheduled_expenses')
    op.drop_index(op.f('ix_scheduled_expenses_scheduled_date'), table_name='scheduled_expenses')
    op.drop_table('scheduled_expenses')
    op.drop_index(op.f('ix_expense_notifications_user_id'), table_name='expense_notifications')
    op.drop_index(op.f('ix_expense_notifications_notification_type'), table_name='expense_notifications')
    op.drop_index(op.f('ix_expense_notifications_is_read'), table_name='expense_notifications')
    op.drop_index(op.f('ix_expense_notifications_created_at'), table_name='expense_notifications')
    op.drop_table('expense_notifications')
    op.drop_index(op.f('ix_recurring_expense_templates_user_id'), table_name='recurring_expense_templates')
    op.drop_index(op.f('ix_recurring_expense_templates_organization_id'), table_name='recurring_expense_templates')
    op.drop_index(op.f('ix_recurring_expense_templates_next_run_date'), table_name='recurring_expense_templates')
    op.drop_index(op.f('ix_recurring_expense_templates_is_active'), table_name='recurring_expense_templates')
    op.drop_index(op.f('ix_recurring_expense_templates_created_at'), table_name='recurring_expense_templates')
    op.drop_table('recurring_expense_templates')
    # ### end Alembic commands ###
