"""Add budget management models

Revision ID: fa97e13a1889
Revises: 7e0145d9e30d
Create Date: 2025-11-07 02:18:11.228403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'fa97e13a1889'
down_revision = '7e0145d9e30d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create budgetperiod enum if it doesn't exist
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'budgetperiod')"))
    if not result.scalar():
        period_enum = postgresql.ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', name='budgetperiod', create_type=False)
        period_enum.create(conn, checkfirst=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', postgresql.ENUM('TRAVEL', 'MEALS', 'SOFTWARE', 'OFFICE_SUPPLIES', 'OTHER', name='expensecategory', create_type=False), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period', postgresql.ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', name='budgetperiod', create_type=False), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), nullable=False),
    sa.Column('critical_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_created_at'), 'budgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_budgets_organization_id'), 'budgets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('budget_id', sa.String(length=255), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_alerts_alert_type'), 'budget_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_budget_alerts_budget_id'), 'budget_alerts', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_alerts_created_at'), 'budget_alerts', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_alerts_created_at'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_budget_id'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_alert_type'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_organization_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_created_at'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
